### ISSUE TITLE
[ADD] SKYTUBE product parser

### ISSUE THREAD

**Issue by EltonChou** [FigureHook/figure_parser#11]
## Source site

[SKYTUBE](https://skytube.jp/)

## Product
[宇佐田 みみ Gold ver. illustration by saitom](https://skytube.jp/item/ax1193mimi_Gold_ver.html)
### Source link

https://skytube.jp/item/ax1193mimi_Gold_ver.html
### Expected output

```yaml
- JAN: null
  adult: true
  category: フィギュア
  copyright: （C） saitom
  distributer: null
  images: https://skytube.jp/files/AX-1193_05.jpg
  manufacturer: SKYTUBE
  name: 宇佐田 みみ Gold ver. illustration by saitom
  og_image: null
  order_period:
    end: 2022-10-28 23:59:59
    start: null
  paintwork: []
  release_infos:
    - price: 20680
      release_date: 2023-05-01 00:00:00
      tax_including: true
  releaser: null
  rerelease: false
  scale: 6
  sculptor:
    - EGG
  series: saitom先生オリジナル
  size: 300
  thumbnail: null
  url: https://skytube.jp/item/ax1193mimi_Gold_ver.html

```
