### ISSUE TITLE
[ADD] FLARE product parser

### ISSUE THREAD

**Issue by EltonChou** [FigureHook/figure_parser#9]
## Source site
[FLARE](https://www.flare-web.jp/index.html)

## Product
[NieR：Automata　2B（ヨルハ二号B型）[DX版]](https://www.flare-web.jp/products/square-enix/figures/2019/09/2b_normal/index.html)
### Source link
https://www.flare-web.jp/products/square-enix/figures/2019/09/2b_normal/index.html

### Expected output

```yaml
- JAN: null
  adult: false
  category: フィギュア
  copyright: ©2017 SQUARE ENIX CO., LTD. All Rights Reserved.
  distributer: 株式会社スクウェア・エニックス
  images: https://www.flare-web.jp/products/square-enix/figures/2019/09/2b_normal/images/image_2b_normal_03.jpg
  manufacturer: 株式会社フレア
  name: NieR：Automata 2B（ヨルハ二号B型）[通常版]
  og_image: null
  order_period:
    end: null
    start: null
  paintwork:
    - 吉沢光正（REFLECT）
  release_infos:
    - price: 15800
      release_date: 2019-09-01 00:00:00
      tax_including: false
    - price: 17380
      release_date: 2021-10-01 00:00:00
      tax_including: true
    - price: 17380
      release_date: 2022-12-01 00:00:00
      tax_including: true
  releaser: 株式会社スクウェア・エニックス
  rerelease: true
  scale: null
  sculptor:
    - 吉沢光正（REFLECT）
    - 東誉之
  series: NieR：Automata（ニーア オートマタ）
  size: 280
  thumbnail: null
  url: https://www.flare-web.jp/products/square-enix/figures/2019/09/2b_normal/index.html
```
